import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';
import businessRules from './sidebars/businessRules';
import modellerAndRulesEngine from './sidebars/modellerAndRulesEngine';
import taskFlow from './sidebars/taskFlow';
import authorisationAndAccess from './sidebars/authorisationAndAccess';
import collaboration from './sidebars/collaboration';
import desktopUIs from './sidebars/desktopUIs';
import webAndAppUIs from './sidebars/webAndAppUIs';
import services from './sidebars/services';
import extensions from './sidebars/extensions';
import repositories from './sidebars/repositories';
import continuousDelivery from './sidebars/continuousDelivery';
import authoring from './sidebars/authoring';
import usoftForAdministrators from './sidebars/usoftForAdministrators';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  sidebar: [
    {
      type: 'doc',
      id: 'Welcome_to_USoft_Knowledge_Base',
      label: 'Getting started',
      customProps: {
        id: 'getting-started-main',
        icon: 'Rocket',
      },
    },
    ...businessRules,
    ...modellerAndRulesEngine,
    ...taskFlow,
    ...authorisationAndAccess,
    ...collaboration,
    ...desktopUIs,
    ...webAndAppUIs,
    ...services,
    ...extensions,
    ...repositories,
    ...continuousDelivery,
    ...authoring,
    ...usoftForAdministrators,
    // {
    //   type: 'autogenerated',
    //   dirName: '.', // '.' means the root of the docs folder
    // }
  ],
};

export default sidebars;
